### ISSUE TITLE
Making your model available through TOMAAT

### ISSUE THREAD

**Issue by faustomilletari** [MiguelMonteiro/ISLES2017#1]
Hello,

I was wondering if you would like to consider making your model available using tomaat. You can find more here https://arxiv.org/abs/1803.06784 and here https://github.com/faustomilletari/TOMAAT

**Comment by MiguelMonteiro** [comment]
Hi,

Thanks for reaching out, I will check it out, what does making it available through tomaat involve (in terms of extra work)?

Btw, aren't you the first author of the V-Net paper?

**Comment by faustomilletari** [comment]
I am. :) 

Fausto Milletarì

**Comment by faustomilletari** [comment]
to make something available via tomaat one should write a script similar to this in python https://github.com/faustomilletari/TOMAAT/blob/master/tomaat/tensorflow/cli.py which basically derived a new class from TOMAATService and writes the functions that implement the inference loop, pre-processing and post processing of the method.

I'm working to make it better, in terms of how easy it is to use. I wish to learn more about more use-cases to see what's I am missing there. 

after making it available one can use it as shown here: https://www.youtube.com/watch?v=rWH5J3QdoNI

**Comment by MiguelMonteiro** [comment]
Ok understood, I don't think I will make this model available though.
The absolute results aren't very good and I have stopped actively developing it. 
That being said, I really like what you are doing and will definitely try it with future models that am working on now.
