### ISSUE TITLE
How the Algorithm Works

### ISSUE THREAD

**Issue by AuliaRizky** [MiguelMonteiro/ISLES2017#2]
Hi Miguel, I am amazed by your work and I just started to learn AI for medical imaging for my bachelor thesis. Could you explain to me how this algorithm works? Or do you have publication about it?

**Comment by MiguelMonteiro** [comment]
Hello,

If you are starting to study this topic now, I would advise doing the Coursera course on machine learning and if you can afford the Coursera deep learning specialization.

Regarding publications, you can read the V-Net paper which is the algorithm that I have used.
Also, you should read the U-Net paper and the Fully convolutional neural networks for semantic segmentation paper.
Just google the names and you will find them.

In addition, there is a joint publication coming out from everyone who participated in the ISLES 2016 and 2017 that describes the methods. The journal is Frontiers in Neurology but it not out yet.

**Comment by AuliaRizky** [comment]
Thank you for your sugestion. 

How about the MR image processing? The image containt few format for each set of data (4DWI, ADC, MTT, and else). Which image did you choose to used?
